version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clinic-sqlserver
    environment:
      MSSQL_SA_PASSWORD: "Clin1c@2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
  test:
    [
      "CMD",
      "/opt/mssql-tools/bin/sqlcmd",
      "-S",
      "localhost",
      "-U",
      "sa",
      "-P",
      "Clin1c@2024",
      "-Q",
      "SELECT 1",
    ]
  interval: 10s
  retries: 10
  start_period: 30s

  api:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    container_name: clinic-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ClinicDb;User=sa;Password=Clin1c@2024;"
    ports:
      - "5000:80"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sql_data:
