
version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clinic-sqlserver
    environment:
      MSSQL_SA_PASSWORD: "Clin1c@2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Clin1c@2024",
        ]
      interval: 10s
      retries: 10
      start_period: 30s

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./script.sql:/script.sql
    entrypoint: >
      /bin/bash -c "
        echo 'Aguardando SQL Server...';
        sleep 20;
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Clin1c@2024 -d master -i /script.sql;
        echo 'Script executado com sucesso!'"

  api:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    container_name: clinic-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ClinicDb;User=sa;Password=Clin1c@2024;Encrypt=False;TrustServerCertificate=True;"
    ports:
      - "5000:80"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sql_data:
